apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-deployment
  labels:
    app: {{ .Values.service.name }}-deployment-label
spec:
  replicas: {{ .Values.replicas.amount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.service.name }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.service.name }}-config
          resources:
            requests:
              memory: {{ .Values.requests.memory | default "200Mi" }}
              cpu: {{ .Values.requests.cpu | default "300m" }}
            limits:
              memory: {{ .Values.limits.memory | default "200Mi" }}
              cpu: {{ .Values.limits.cpu | default "300m" }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.service.name }}
  ports:
    - name: {{ .Values.service.name }}-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
