version: '3.8'

x-all-services: &all-services
  AUTH_SERVICE: ${AUTH_SERVICE}

services:
  nginx-gateway:
    image: nginx:1.25.3-alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ${AUTH_SERVICE}
    environment:
      AUTH_SERVICE_URL: ${AUTH_SERVICE}:${AUTH_SERVICE_PORT}
    networks:
      - auth_network

  auth-service:
    build:
      context: ../${AUTH_SERVICE}
      dockerfile: Dockerfile
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    # restart: unless-stopped
    depends_on: 
      - redis-whitelist
      - postgres-db
    environment:
      <<: [*all-services]
      REDIS_HOST: redis-whitelist
      DB_HOST: postgres-db
      ACCESS_TOKEN_PUBLIC_SECRET_PATH: /app/cert/access.pub
      ACCESS_TOKEN_PRIVATE_SECRET_PATH: /app/cert/access
    networks:
      - auth_network

  postgres-db:
    image: postgres:16.1
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_PORT: 5432
    networks:
      - auth_network

  redis-whitelist:
    container_name: redis-whitelist
    image: redis:7.0.11
    ports:
      - 6379:6379
    command: redis-server --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis-whitelist-volume:/data
    networks:
      - auth_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    # restart: always
    ports:
      - "8888:80"
    environment:
      # host.docker.internal instead of localhost while connecting to DB in pgAdmin 
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    depends_on:
      - postgres-db
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    networks:
      - auth_network

volumes:
  postgres_db_volume:
  pgadmin_volume:
  redis-whitelist-volume:

networks:
  auth_network:   
    driver: bridge 