apiVersion: v1
kind: ConfigMap
metadata:
  name: registration-config
data:
  SERVER_PORT: "5002"
  #
  USER_SERVICE_HOST: "user-service"
  USER_SERVICE_GRPC_PORT: "6003"
  #
  DB_NAME: "registration-service"
  #
  LOG_LEVEL: "4"
  GIN_MODE: "debug"
