apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: k8s-notification-service:v1
          # command: ["sleep", "3600"]
          ports:
            - containerPort: 5004
          envFrom:
            - configMapRef:
                name: notification-config
          resources:
            requests:
              memory: 200Mi
              cpu: 300m
            limits:
              memory: 200Mi
              cpu: 300m

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification
  ports:
    - name: notification-port
      port: 5004
      targetPort: 5004
