apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12.11-management
          # command: ["sleep", "3600"]
          ports:
            - containerPort: 15672
            - containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
          resources:
            requests:
              memory: 200Mi
              cpu: 300m
            limits:
              memory: 200Mi
              cpu: 300m
      volumes:
        - name: rabbitmq-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-port
      port: 5672
      targetPort: 5672
    - name: rabbitmq-client-port
      port: 15672
      targetPort: 15672
