apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: k8s-user-service:v1
          # command: ["sleep", "3600"]
          ports:
            - containerPort: 5003
            - containerPort: 6003
          envFrom:
            - configMapRef:
                name: user-config
            - configMapRef:
                name: postgres-shared-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password-secret
                  key: password
          resources:
            requests:
              memory: 200Mi
              cpu: 300m
            limits:
              memory: 200Mi
              cpu: 300m

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: user-port
      port: 5003
      targetPort: 5003
    - name: user-port-grpc
      port: 6003
      targetPort: 6003
