service:
  name: notification
  port: 5004

image:
  name: k8s-notification-service
  tag: v1

replicas:
  amount: 1

env:
  RABBIT_MQ_CONNECTION: "amqp://root:1234@rabbitmq-service:5672/"
  LOG_LEVEL: "4"
