hasGrpcServer: true
hasDbConfig: true

service:
  name: user
  port: 5003
  grpcPort: 6003

image:
  name: k8s-user-service
  tag: v1

replicas:
  amount: 1

env:
  GRPC_SERVER_PORT: "6003"
  #
  DB_NAME: "user-service"
  #
  LOG_LEVEL: "4"
  GIN_MODE: "debug"
